# TEMPLATE - PYTHON 101


# BASICS


In [2]:
a = [1, 23, 3, 4]

b = a.pop()

4
[1, 23, 3]


In [20]:
################## PYTHON BASICS #######################

my_var = None # --> null, nullptr
#########################################
############ String #####################
#########################################
string = "String _ tEst"
char = 's'
#LOWER / UPPER CHARACTERS
string = string.lower()
string = string.upper()
# check if char is letter
char.isalpha()
# check if character is a number 
char.isnumeric()


# string[start:end:step]
# delete the 1st two chars of a string
string = string[2:] 

# reverse string
string = string[::-1]

# replaces in all string
str.replace(old, new[, max]) 

#########################################
############ arrays aka lists ###########
#########################################

my_list = [1, 2, 4, 5, 6]
del my_list[2]      # delete element by index
my_list.remove(2)   # remove element by element


###### Casting ######
str_num = "23"
num = int(str_num) # --> 23

#########################################
######### BINARY REPRESENTAION ##########
#########################################
num = bin(5)
# --> 0b101


# class syntax
class Mammal:
  def walk(self):
    print("walk")
#parent class inside the brackets
class Dog(Mammal):
    def bark(self):
        print("bark")
#pass doesnt really mean anything
#python doesnt like empty classes
class Cat(Mammal):
    pass
#creaing a dog object
dog1 = Dog()
dog1.walk()
dog1.bark()


False

# Data Structuers

In [ ]:
# Linked List
# Node class
class Node:
  
    # Function to initialize the node object
    def __init__(self, data):
        self.data = data  # Assign data
        self.next = None  # Initialize
                          # next as null
  
# Linked List class
class LinkedList:
    
    # Function to initialize the Linked
    # List object
    def __init__(self):
        self.head = None
        
        
# Definition for singly-linked list.
class ListNode(object):
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
# Definition for a binary tree node.
class TreeNode(object):
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

# Numpy 101


In [3]:
# basics
# creating arrays

myarray = np.array([1, 2, 3])
my2darray = np.array([[1, 2, 3], [4, 5, 6]])

## Get dimension of numpy arrays.
myarray.ndim 
my2darray.ndim

## Num of rows and cols within the array.
my2darray.shape

## Get item size of the elements of the array
my2darray.itemsize

## Get total size
my2darray.nbytes

24

- Accessing/Changing specific elements, rows, columns, etc.

In [4]:
myarray = np.array([[1, 2, 3, 4 ,5 ,6 ,7],[8, 9, 10, 11, 12, 13, 14]])

## Get a specific element [row, col]
print(myarray[1, 5])

## Get a specifc row
print(myarray[0, :])

## Get a specific col
print(myarray[:, 2])

## Getting fancy [startindex, endindex, stepsize]
print(myarray[0, 1:6:2])

## Changing element
myarray[1, 5] = 20

## Replacing an entire column
myarray[:, 2] = [1, 2]
myarray

13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

- Initializing Different Types of Arrays.

In [5]:
## ALL 0's Array
np.zeros((3, 4))

## ALL 1's Matrix
np.ones((2, 2))

## Any other number
np.full((2, 4), 69)

## Any other full-like
np.full_like(myarray, 4)

## Random integer values
np.random.randint(1, 100, size=(2, 2))

## Identity Matrix, square-shaped matrix
np.identity(3)

## Repeat an element based upon different axis points
newArray = np.array([[1,2,3]])
e1 = np.repeat(newArray, 3, axis=0)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

- Math


In [ ]:
a = np.array([1, 2 ,3 ,4])

## Array element operations.
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

## Get the sin of every element within an array
print(np.sin(a))
print(np.cos(a))
print(np.cosh(a))
print(np.tan(a))


- Linear Algebra

In [6]:
## Multiplying matrices
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

## finding the identity matrix
c = np.identity(3)
np.linalg.det(c)

array([[1., 1.],
       [1., 1.]])

# Pandas

In [ ]:
import pandas as pd